### ISSUE TITLE
List style issues

### ISSUE THREAD

**Issue by treyhunner** [rvben/rumdl#42]
There are a number of interesting things about these lists, so I'm not certain where the exact issue lies.

```md
# The 4 ways to import a module

There are four different ways to import:

1. Import the whole module using its original name:

    ```python
    import random
    ```

2. Import specific things from the module:

    ```python
    from random import choice, randint
    ```

3. Import the whole module and rename it, usually using a shorter variable name:

    ```python
    import pandas as pd
    ```

4. Import specific things from the module and rename them as you're importing them:

    ```python
    from os.path import join as join_path
    ```

That last one is usually done to avoid a name collision or *sometimes* to make a more descriptive name (though that's not very common).

## My recommendations

1. Use `from` for **short and descriptive variable names**
    I tend to use the `from` syntax most (number 2 above) because I prefer **short and descriptive variable names**.

2. Import the whole module if needed **to avoid ambiguity**.
    If there's a name like `choice` that isn't as clear as `random.choice`, then I prefer to import the whole module for a more descriptive name

3. **Avoid renaming imports**.
    I very rarely use the `as` syntax (unless I'm in the `pandas` or `numpy` worlds, where it's common convention).
    And I almost never use the `as` syntax with `from` unless I'm avoiding a name collision.
```

I believe those lists have a correct format, but this file fails to lint:

```bash
$ uv tool run rumdl check --disable MD013 file13.md
file13.md:29:1: [MD029-style] List continuation should be indented (lazy continuation detected) [*]
file13.md:31:1: [MD029-style] List continuation should be indented (lazy continuation detected) [*]
file13.md:33:1: [MD029] Ordered list item number 1 does not match style (expected 5) [*]
file13.md:36:1: [MD029] Ordered list item number 2 does not match style (expected 6) [*]
file13.md:39:1: [MD029] Ordered list item number 3 does not match style (expected 7) [*]

Issues: Found 5 issues in 1 file (33ms)
Run with `--fix` to automatically fix 5 of the 5 issues
```

**Comment by rvben** [comment]
⚠️ **Partially Fixed in v0.0.113**

**Fixed:**
- Headings are no longer incorrectly flagged as lazy continuation
- Improved list grouping logic to better detect structural separators

**Still needs work:**
- The core issue with list block parsing when lists contain indented code blocks
- Lists separated by headings may still be treated as continuous in some cases

The fundamental issue is in the list block boundary detection algorithm. A complete fix would require significant changes to the list parsing logic in LintContext. I'll look into this separately as this will take a bit more effort.

**Comment by rvben** [comment]
This should be now completely fixed in 0.0.116. Let me know if you encounter any issues.

This issue, and other issues you've raised, have been very helpful to improve the quality for everyone. Thanks!

**Comment by treyhunner** [comment]
Your quick fixing of these issues is making it exceedingly likely that I will be running rumdl in 2 of my CI systems to lint hundreds of markdown files. 

Thanks @rvben !

**Comment by treyhunner** [comment]
@rvben I believe this is still an issue because I can still reproduce the original error.

```bash
$ uv tool run --with rumdl==0.0.116 rumdl check  --disable MD013 file13.md
file13.md:29:1: [MD029-style] List continuation should be indented (lazy continuation detected) [*]
file13.md:33:1: [MD029] Ordered list item number 1 does not match style (expected 5) [*]
file13.md:36:1: [MD029] Ordered list item number 2 does not match style (expected 6) [*]
file13.md:39:1: [MD029] Ordered list item number 3 does not match style (expected 7) [*]

Issues: Found 4 issues in 1 file (33ms)
Run with `--fix` to automatically fix 4 of the 4 issues
```

I tested with versions 0.0.115, 0.0.116, 0.0.117, and 0.0.118.

**Comment by rvben** [comment]
Thanks @treyhunner for testing this out with multiple versions, and providing the feedback.

I've been looking mostly at the other type of issues last days. I'll try to have a look at this one again and #52 today, because the lists definitely are not perfectly handled.

**Comment by rvben** [comment]
Some structural improvements were needed with how lists were parsed and potential seperations were interpreted. All those improvements landed in 0.0.120. Thanks again for the very useful feedback, @treyhunner .
