### ISSUE TITLE
Struggling with the pre-commit configuration

### ISSUE THREAD

**Issue by kattni** [rvben/rumdl#71]
Hello!

I am working on integrating `rumdl` into my test project as a first step. I created a `.rumdl.config` file, and running `rumdl` directly passes. I'm trying to configure pre-commit, and failing to do so. I can't figure out the `exclude` syntax. It's not paying any attention to my `.rumdl.toml` file, though I get the impression that's not how it works. I need to exclude a couple of files, and disable a couple of rules. 

I'd greatly appreciate some assistance. 

Thank you!

**Comment by rvben** [comment]
Hi @kattni,

There were indeed some issues with the pre-commit and how it handled the configurations. By default it should just use the config file, and that was not the case. That is now fixed.

Is your issue completely resolved now?

**Comment by kattni** [comment]
Hi @rvben,

The issue is only partially fixed. pre-commit is ignoring my `exclude =` in my `.rumdl.toml` file. So, it's currently failing on the two files I need to exclude from checks. 

Please let me know if I'm missing something. Thanks!

**Comment by rvben** [comment]
Ah, that could be because of how the excluding works if files/paths are explicitly provided. "rumdl check README.md' checks the README.md even if it's part of the exclude, because "why else would someone do that?" was my thought. Well, in pre-commit hooks for example, I just realized. 

I have to look at this and compare it to how other tools handle this.

**Comment by kattni** [comment]
I had a thought - could you make the way excluding works configurable? Have it default to the current behavior, but add the ability to tell it to prioritise the exclude file/path list over the explicitly provided file/path list? You probably already considered this, but it popped into my head, so I figured I would share.

**Comment by rvben** [comment]
@kattni, good suggestion. I just looked at [ruff](https://docs.astral.sh/ruff/settings/#force-exclude) and they do something similar to what you're suggesting, so I'll implement it the same way. This should land in next release.
